In [3]:
# Timing Code Execution: %timeit
%timeit L = [n ** 2 for n in range(1000)]

234 µs ± 561 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
# %timeit
%time L = [n ** 2 for n in range(1000)]

CPU times: user 314 µs, sys: 8 µs, total: 322 µs
Wall time: 324 µs


In [14]:
# Make a List 
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
l1 = [str(x) for x in l]
l2 = [str(x) for x in list(range(10))]
l1,l2

(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])

In [18]:
# Fixed-Type Arrays in Python
import array
L = list(range(10))
# 'i' is a type code indicating the contents are integers.
A = array.array('i', L)
L, A

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [21]:
import numpy as np
np.array([3, 4, 2, 3])

array([3, 4, 2, 3])

In [23]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [24]:
# Create a length-10 integer array filled with zeros 
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# Create a 3x5 floating-point array filled with 1s 
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
# Create a 3x5 array filled with 1.2 
np.full((3, 5), 1.2)

array([[1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2]])

In [29]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function) 
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [32]:
# Create an array of five values evenly spaced between 0 and 1 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
# Create a 3x3 array of uniformly distributed # random values between 0 and 1
np.random.random((3, 3))

array([[0.40233151, 0.93961496, 0.61579911],
       [0.16854041, 0.49070901, 0.38031222],
       [0.34515369, 0.7493968 , 0.15982783]])

In [34]:
# Create a 3x3 array of normally distributed random values # with mean 0 and standard deviation 1 
np.random.normal(0, 1, (3, 3))

array([[ 1.12736526, -0.52180255,  0.82964569],
       [-0.17644613,  0.3860925 , -1.9765738 ],
       [-1.59400099, -0.66591978,  1.55944065]])

In [35]:
# Create a 3x3 array of random integers in the interval [0, 10) 
np.random.randint(0, 10, (3, 3))

array([[0, 4, 0],
       [8, 0, 1],
       [0, 9, 6]])

In [36]:
# Create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that # memory location
np.empty(3)

array([1., 1., 1.])

In [58]:
# NumPy Array Attributes
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
x = [x1,x2,x3]
for i in range(3):
    print(f'x{i+1} ndim: {x[i].ndim} --- x{i+1} shape: {x[i].shape}--- x{i+1} size: {x[i].size} --- x{i+1} dtype: {x[i].dtype}')
    print(x[i],"\n")

x1 ndim: 1 --- x1 shape: (6,)--- x1 size: 6 --- x1 dtype: int64
[5 0 3 3 7 9] 

x2 ndim: 2 --- x2 shape: (3, 4)--- x2 size: 12 --- x2 dtype: int64
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

x3 ndim: 3 --- x3 shape: (3, 4, 5)--- x3 size: 60 --- x3 dtype: int64
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]] 



In [62]:
a = np.arange(0, 20, 2)
a, a[0], a[-1]


(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]), 0, 18)

In [65]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [72]:
x2[0,0], x2[-1,-1]

(3, 7, array([[3, 5, 2, 4]]), array([[3, 5, 2, 4],
        [7, 6, 8, 8]]))

In [73]:
x2[:1], x2[:2]

(array([[3, 5, 2, 4]]), array([[3, 5, 2, 4],
        [7, 6, 8, 8]]))

In [74]:
x2[::2] # every other element

array([[3, 5, 2, 4],
       [1, 6, 7, 7]])

In [78]:
x1, x1[1::2] # every other element, starting at index 1

(array([5, 0, 3, 3, 7, 9]), array([0, 3, 9]))

In [79]:
x1[::-1] # all elements, reversed

array([9, 7, 3, 3, 0, 5])

In [87]:
# X2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [88]:
x2[:2, :3] # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [89]:
x2[:3, ::2] # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [90]:
x2[::-1]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [91]:
x2[::-1, ::-1] # subarray dimensions can even be reversed together

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [93]:
print(x2[:, 0]) # first column of x2
print(x2[0, :]) # first row of x2

[3 7 1]
[3 5 2 4]


In [98]:
x2_sub = x2[:2, :2] 
print(x2,"\n\n", x2_sub)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

 [[3 5]
 [7 6]]


## Reshaping of Arrays

In [103]:
arr = np.arange(1, 13)
grid = arr.reshape((4, 3)) 
print(arr)
print(grid)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [105]:
rid = arr.reshape((2, 6)) 
print(arr)
print(rid)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## Array Concatenation and Splitting

In [107]:
x = np.array([1, 2, 3]) 
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [108]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
# concatenate along the first axis 
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [111]:
# concatenate along the second axis (zero-indexed) 
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Splitting of arrays

In [112]:
x=[1,2,3,99,99,3,2,1] 
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [116]:
x1, x2, x3 = np.split(x, [2, 5])
print(x1, x2, x3)

[1 2] [ 3 99 99] [3 2 1]


In [117]:
grid = np.arange(16).reshape((4, 4)) 
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
upper, lower = np.vsplit(grid, [2]) 
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [119]:
left, right = np.hsplit(grid, [2]) 
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Array arithmetic

In [136]:
x = np.arange(4) 
print("x =", x)
print("x + 5 =", x + 5, np.add(x, 5)) 
print("x - 5 =", x - 5) 
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x) 
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8] [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [134]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [135]:
np.add(x, 2)

array([2, 3, 4, 5])

## Reduce Accumulate Outer

In [138]:
x = np.arange(1, 6) 
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [140]:
np.multiply.reduce(x)

120

In [141]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [142]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [143]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [146]:
L = np.random.random(10)
print(L)
sum(L)

[0.36549611 0.01662797 0.23074234 0.7649117  0.94412352 0.74999925
 0.33940382 0.48954894 0.33898512 0.17949026]


4.419329016644731

In [148]:
min(L), max(L), L.sum()

(0.016627973733867263, 0.9441235194354546, 4.419329016644731)

In [153]:
M = np.random.random((3, 4))
M

array([[0.94411975, 0.60825287, 0.59665541, 0.78364425],
       [0.5000263 , 0.05037006, 0.69909807, 0.9923964 ],
       [0.26726254, 0.67909062, 0.86428144, 0.75084425]])

In [154]:
M.min(axis=0) # minimum value in each column 

array([0.26726254, 0.05037006, 0.59665541, 0.75084425])

In [155]:
M.min(axis=1) # minimum value in each row 

array([0.59665541, 0.05037006, 0.26726254])

In [171]:
p = np.arange(5,15)
p, np.argmin(p)

(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), 0)

In [167]:
np.argmax(M)

7